/* Replace with your SQL commands */

CREATE TABLE IF NOT EXISTS survey (
	id INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	age INT NOT NULL,
	sex TINYINT NOT NULL,
	address VARCHAR(255) NOT NULL,
	interested TINYINT DEFAULT 0 NOT NULL,
	reason TEXT NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);